### ISSUE TITLE
[Nav] Fix navbar alignment

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#12]
The hamburger menu gives up it's alignment in tablet mode and in mobile mode (where it will drop down). I tried to adjust aligning with CSS in Navbar.toggle (which is hamburger menu) but it won't bulge as I cannot overwrite bootstrap styling I guess. I even tried to move all the elements as well but it won't even give some signs

<img width="393" alt="Screen Shot 2022-06-29 at 4 16 04 PM" src="https://user-images.githubusercontent.com/68720970/176543241-b61c2776-0fde-4a16-bdb1-9b1632ed6534.png">
<img width="930" alt="Screen Shot 2022-06-29 at 4 14 55 PM" src="https://user-images.githubusercontent.com/68720970/176543261-dc62744d-97e5-4caa-a70c-1c44ec5a21d2.png">

**Comment by juliazib** [comment]
Hey, @parthmarfatia! What's your discord username if you don't mind sharing? I'm juliaz and go by Julia on the Mbrlla Hacks server.

**Comment by parthmarfatia** [comment]
zapzap#3401
@juliazib

**Comment by parthmarfatia** [comment]
#31 resolved this issue. Kindly review pull request.
