### ISSUE TITLE
[Main] Fix the "Notified" Button

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#18]
Cannot click the button, not sure what is the reason because it has the same jsx and css as sponsor button

Home Page:
<img width="460" alt="Screen Shot 2022-07-03 at 9 53 59 PM" src="https://user-images.githubusercontent.com/68720970/177068176-901b7b1d-6c89-4cec-ae6a-2150c80a9a93.png">

<img width="474" alt="Screen Shot 2022-07-03 at 9 54 31 PM" src="https://user-images.githubusercontent.com/68720970/177068220-2d44fe38-c180-4ee2-9dd0-203fafeb1fba.png">

**Comment by AsaiToshiya** [comment]
Try to remove z-index from `.home-section` in `home.css`.

https://github.com/MbrllaHacks/Website/blob/c9526d9efc9c39e9af0ee55d021f6a0558e307ca/src/components/Home/home.css#L50
