### ISSUE TITLE
[Team] Create Section

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#19]
Link to design: [Figma](https://www.figma.com/file/Mlv3IXcPfdSWc1iSPkBzos/mbrllahacks-website?node-id=0%3A1)

Bonus if you can add hover animation too. Upon hovering it should pop up the umbrella 

<img width="593" alt="Screen Shot 2022-07-03 at 10 22 13 PM" src="https://user-images.githubusercontent.com/68720970/177070570-ab1d23a4-a137-4862-9c1c-4332f5d7ec8d.png">

**Comment by samyak112** [comment]
Hello, I am interested in this , can you assign this to me? I have some experience in react.
