### ISSUE TITLE
[FAQ] Improve Dropdown and styling

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#41]
Design:
<img width="677" alt="Screen Shot 2022-07-05 at 5 40 00 PM" src="https://user-images.githubusercontent.com/68720970/177421036-f076a79b-0f96-496f-8b25-dbc63a2480a6.png">

Current:
<img width="1356" alt="Screen Shot 2022-07-05 at 5 40 26 PM" src="https://user-images.githubusercontent.com/68720970/177421094-8a86c1cf-daf4-4573-8d54-408ee3e6754d.png">

**Comment by samyak112** [comment]
Hey, If this issue is still open I can work on it , so please consider to assign this to me too.

**Comment by Hiten1708** [comment]
[](url)
