### ISSUE TITLE
[Nav - Contact] Update social icons

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#53]
- Please remove the @ in contact section and navbar. 
- Add LinkedIn and YouTube icons in both sections
![image](https://user-images.githubusercontent.com/68720970/177895561-892524f3-2f58-41bd-bc75-a67329829555.jpeg)
![image](https://user-images.githubusercontent.com/68720970/177895569-49fc5882-ea81-49c2-829d-22d9e4d994dd.jpeg)

**Comment by jaganbabu0506** [comment]
i will support for this item
