### ISSUE TITLE
[Home] Change the "Get notified" link

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#55]
Update the link in that button to this https://forms.gle/Nw7pjuKdSwySp1Wf8

<img width="375" alt="Screen Shot 2022-07-07 at 9 32 08 PM" src="https://user-images.githubusercontent.com/68720970/177898631-e5cdd052-bb89-45aa-a9d6-d36b5cc2e3a3.png">
<img width="435" alt="Screen Shot 2022-07-07 at 9 34 35 PM" src="https://user-images.githubusercontent.com/68720970/177898862-b28b3cd4-7692-4b18-9be8-5837fad75360.png">

**Comment by msabirz** [comment]
Is this resolved?

**Comment by rohitroy-github** [comment]
I wanna work on this issue.

**Comment by msabirz** [comment]
What do you think why I asked him that is it resolved or not 🤣
