### ISSUE TITLE
[Contact] Change the "Send" button link

### ISSUE THREAD

**Issue by Hiten1708** [MbrllaHacks/Website#57]
Change the send button link so that it will redirect clickers to contact@mbrllahacks.ca

<img width="445" alt="Screen Shot 2022-07-07 at 10 31 02 PM" src="https://user-images.githubusercontent.com/68720970/177905023-7d85dd1b-1411-458e-a711-1ef30135769b.png">

**Comment by sumanparajuli** [comment]
Sir Please assign this issue to me. I can solve this issue easily

**Comment by jaganbabu0506** [comment]
this issue fixed in PR: (https://github.com/MbrllaHacks/Website/pull/60)

**Comment by msabirz** [comment]
Please close this issue
