### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by FengchiW** [MbrllaHacks/Website#6]
-> Openable menus
Ensure this would be easy enough to add an remove things!

![image](https://user-images.githubusercontent.com/13229535/175797685-52b84a4f-1b85-401c-9868-2ad6d67fb97e.png)

**Comment by Hiten1708** [comment]
@amishasao , Can we please have a update on your work?

**Comment by amishasao** [comment]
I'm almost done with functionality, just working on styling. I'll have it done by tomorrow.
