### ISSUE TITLE
[Images] Load a low res image first then a highres one

### ISSUE THREAD

**Issue by FengchiW** [MbrllaHacks/Website#63]
https://stackoverflow.com/questions/27934548/load-a-low-res-background-image-first-then-a-high-res-one

![image](https://user-images.githubusercontent.com/13229535/178073128-d5b788d9-d68d-4aab-8198-7263f8041632.png)
![image](https://user-images.githubusercontent.com/13229535/178073145-05e4ab94-2547-4925-9f04-3437a5ca8a42.png)

**Comment by Hiten1708** [comment]
Resolved
