### ISSUE TITLE
[All pages] - Fix all these minor warnings (mostly alt text)

### ISSUE THREAD

**Issue by FengchiW** [MbrllaHacks/Website#70]
Warning
(6:29521) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
src/components/About/about.js
  Line 6:30:  'Particle' is defined but never used  no-unused-vars
src/components/Contact/contact.js
  Line 1:8:    'a' is defined but never used                                                                              no-unused-vars
  Line 6:8:    'prin' is defined but never used                                                                           no-unused-vars
  Line [35](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:36):17:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [38](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:39):17:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [41](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:42):17:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
src/components/Faq/faq.js
  Line 5:8:    'fancyUnderline' is defined but never used                                                                 no-unused-vars
  Line 13:21:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
src/components/Faq/questions.js
  Line 2:10:  'Container' is defined but never used  no-unused-vars
  Line 2:26:  'Col' is defined but never used        no-unused-vars
  Line 4:10:  'useRef' is defined but never used     no-unused-vars
src/components/Footer/footer.js
  Line 1:8:   'logo' is defined but never used      no-unused-vars
  Line 2:8:   'a' is defined but never used         no-unused-vars
  Line 3:8:   'disc' is defined but never used      no-unused-vars
  Line 4:8:   'twitter' is defined but never used   no-unused-vars
  Line 5:8:   'insta' is defined but never used     no-unused-vars
  Line 8:31:  'Particle' is defined but never used  no-unused-vars
src/components/Home/home.js
  Line 4:30:   'Particle' is defined but never used                                                                       no-unused-vars
  Line 32:25:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
src/components/Navbar/navbar.js
  Line 3:8:    'a' is defined but never used                                                                              no-unused-vars
  Line 16:11:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [46](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:47):15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [49](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:50):15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [52](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:53):15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [56](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:57):15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
  Line [60](https://github.com/MbrllaHacks/Website/runs/7267770206?check_suite_focus=true#step:3:61):15:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

**Comment by nitin094-hub** [comment]
Can I take up this issue?

**Comment by nitin094-hub** [comment]
What should I add in alt text?

**Comment by FengchiW** [comment]
Whatever makes sense try to pull from context

**Comment by Hiten1708** [comment]
I'll keep this open as it will be good idea to work on this issue after we have completed the website.

**Comment by Hiten1708** [comment]
Oops
